import sys
import logging
from datetime import datetime
from dateutil.relativedelta import relativedelta
from pyspark.sql import SparkSession

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def build_gr_mobile_datamart(spark, logical_date, logger):
    from pyspark.sql import functions as F

    business_month_end = logical_date + relativedelta(months=1, days=-1)

    cp_mobile_daily_history_df = spark.table('gr_dm_sec.cp_mobile_daily_history')
    
    daily_features = (
        cp_mobile_daily_history_df
        .withColumn('tp_change_days',
                    F.datediff(F.to_date(F.lit(business_month_end)), F.to_date('tp_change_dt')))
        .withColumn('max_subs_fee_day_31d_days_ago',
                    F.datediff(F.to_date(F.lit(business_month_end)), F.to_date('max_subs_fee_dt_day_31d')))
        .withColumn('ep_tp_change_days',
                    F.datediff(F.to_date(F.lit(business_month_end)), F.to_date('ep_tp_change_dt')))
        .withColumn('device_first_imei_msisdn_days',
                    F.datediff(F.to_date(F.lit(business_month_end)), F.to_date('device_first_imei_msisdn_dt')))
        .withColumn('device_first_imei_msisdn_days',
                    F.datediff(F.to_date(F.lit(business_month_end)), F.to_date('device_first_imei_msisdn_dt')))
        .withColumn('last_change_smartphone_days',
                    F.datediff(F.to_date(F.lit(business_month_end)), F.to_date('last_change_smartphone_dt')))
        .withColumn('start_use_cur_smartp_mod_days',
                    F.datediff(F.to_date(F.lit(business_month_end)), F.to_date('start_use_cur_smartp_mod_dt')))
        .withColumn('mymts_max_activity_master_days',
                    F.datediff(F.to_date(F.lit(business_month_end)), F.to_date('mymts_max_activity_master_dt')))
        .withColumn('mymts_max_activity_slave_days',
                    F.datediff(F.to_date(F.lit(business_month_end)), F.to_date('mymts_max_activity_slave_dt')))
        .withColumn('mnp_portation_in_mts_days',
                    F.datediff(F.to_date(F.lit(business_month_end)), F.to_date('mnp_portation_in_mts_dt')))
        .withColumn('last_active_roam_day_90d_days_ago',
                    F.datediff(F.to_date(F.lit(business_month_end)), F.to_date('last_active_roam_dt_day_90d')))
        .select(
            'app_n',
            'regid',
            'msisdn',
            'bill_group_name',
            'lifetime',
            'm_categ_name',
            'm_reg_cd',
            'm_reg_name',
            'sale_channel_cd',
            'sale_channel_name',
            'fl_client_name_confirmed',
            'client_type_cd',
            'sex',
            'age',
            'citizenship_type',
            'foreign_citizenship_cd',
            'region_name',
            'msisdn_type_cd',
            'msisdn_cluster',
            'trust_category',
            'credit_limit_value',
            'cnt_app_on_acc',
            'service_provider_cd',
            'fl_push_off',
            'fl_unlim_internet',
            'max_subs_fee_day_31d',
            'tp_change_days',
            'host_type',
            'activity_on_bts_dur_day_30d',
            'cnt_give_out_prizes_day_7d',
            'cnt_give_out_prizes_day_30d',
            'cnt_give_out_prizes_day_90d',
            'cnt_give_out_prizes_day_180d',
            'tp_name',
            'tp_type_name',
            'tp_group_name',
            'max_subs_fee_day_31d_days_ago',
            'tp_current_use_dur',
            'tp_fl_unlim_internet',
            'tp_on_act_cd',
            'tp_prev_cd',
            'ep_tp_id',
            'ep_tp_name',
            'ep_tp_change_days',
            'ep_tp_cnt_gb',
            'ep_tp_cnt_min',
            'ep_tp_cnt_sms',
            'ep_tp_pay_method_name',
            'ep_tp_prev_name',
            'ep_tp_service_channel_name',
            'ep_tp_status',
            'ep_tp_version',
            'ep_tp_fl_ppd_current',
            'ep_tp_fl_ppd_day_30d',
            'ep_tp_fl_ppd_day_90d',
            'ep_tp_fl_ppm_current',
            'ep_tp_fl_ppm_day_30d',
            'ep_tp_fl_ppm_day_90d',
            'device_best_support_g',
            'device_first_imei_msisdn_days',
            'device_model',
            'device_os_name',
            'device_os_name_prev',
            'device_os_version',
            'device_type',
            'device_type_prev',
            'device_vendor',
            'cnt_smartphone_all_time',
            'smartphone_use_dur_avg',
            'last_change_smartphone_days',
            'start_use_cur_smartp_mod_days',
            'mymts_fl_app_day_30d',
            'mymts_fl_activity_day_90d',
            'mymts_fl_wps',
            'mymts_fl_app_push_on',
            'mymts_fl_activity_master_day_30d',
            'mymts_fl_activity_master_day_90d',
            'mymts_max_activity_master_days',
            'mymts_max_activity_slave_days',
            'mymts_version_app_str',
            'mymts_version_app',
            'fl_mnp_out',
            'fl_mnp_request',
            'mnp_portation_in_mts_days',
            'cc_fl_bill_group',
            'cc_fl_bill_group_b2b',
            'cc_fl_full',
            'cc_fl_full_b2b',
            'cc_fl_full_rtm',
            'cc_fl_m_categ',
            'cc_fl_m_categ_b2b',
            'cc_fl_other',
            'cc_fl_other_all',
            'cc_fl_other_b2b',
            'cc_fl_tp',
            'cc_fl_tp_b2b',
            'prcnt_dur_2g_day_30d',
            'prcnt_dur_3g_day_30d',
            'prcnt_dur_4g_day_30d',
            'prcnt_dur_no_signal_day_30d',
            'cnt_sms_vamzvonili_day_30d',
            'cnt_sms_yanasvyazi_day_30d',
            'fl_user_active_day_7d',
            'fl_user_active_day_30d',
            'fl_signal_traffic_activity_day_1d',
            'fl_signal_traffic_activity_day_3d',
            'fl_signal_traffic_activity_day_7d',
            'fl_last_active_roam_day_90d',
            'last_active_roam_day_90d_days_ago',
            'tg_traf_vol_day_7d',
            'tg_traf_vol_day_30d',
            'tg_traf_vol_day_90d',
            'tg_traf_vol_day_360d',
            'wa_traf_vol_day_7d',
            'wa_traf_vol_day_30d',
            'wa_traf_vol_day_90d',
            'wa_traf_vol_day_360d',
            'wc_traf_vol_day_7d',
            'wc_traf_vol_day_30d',
            'wc_traf_vol_day_90d',
            'wc_traf_vol_day_360d',
            'vi_traf_vol_day_7d',
            'vi_traf_vol_day_30d',
            'vi_traf_vol_day_90d',
            'vi_traf_vol_day_360d',
            'sc_traf_vol_day_7d',
            'sc_traf_vol_day_30d',
            'sc_traf_vol_day_90d',
            'sc_traf_vol_day_360d',
            'vk_traf_vol_day_7d',
            'vk_traf_vol_day_30d',
            'vk_traf_vol_day_90d',
            'vk_traf_vol_day_360d',
            'ok_traf_vol_day_7d',
            'ok_traf_vol_day_30d',
            'ok_traf_vol_day_90d',
            'ok_traf_vol_day_360d',
            'inst_traf_vol_day_7d',
            'inst_traf_vol_day_30d',
            'inst_traf_vol_day_90d',
            'inst_traf_vol_day_360d',
            'x_traf_vol_day_7d',
            'x_traf_vol_day_30d',
            'x_traf_vol_day_90d',
            'x_traf_vol_day_360d',
            'fb_traf_vol_day_7d',
            'fb_traf_vol_day_30d',
            'fb_traf_vol_day_90d',
            'fb_traf_vol_day_360d',
            'tt_traf_vol_day_7d',
            'tt_traf_vol_day_30d',
            'tt_traf_vol_day_90d',
            'tt_traf_vol_day_360d',
            'lk_traf_vol_day_7d',
            'lk_traf_vol_day_30d',
            'lk_traf_vol_day_90d',
            'lk_traf_vol_day_360d',
            'yt_traf_vol_day_7d',
            'yt_traf_vol_day_30d',
            'yt_traf_vol_day_90d',
            'yt_traf_vol_day_360d',
            'rt_traf_vol_day_7d',
            'rt_traf_vol_day_30d',
            'rt_traf_vol_day_90d',
            'rt_traf_vol_day_360d',
            'vkvid_traf_vol_day_7d',
            'vkvid_traf_vol_day_30d',
            'vkvid_traf_vol_day_90d',
            'vkvid_traf_vol_day_360d',
            'tw_traf_vol_day_7d',
            'tw_traf_vol_day_30d',
            'tw_traf_vol_day_90d',
            'tw_traf_vol_day_360d',
            'kion_traf_vol_day_7d',
            'kion_traf_vol_day_30d',
            'kion_traf_vol_day_90d',
            'kion_traf_vol_day_360d',
            'kp_traf_vol_day_7d',
            'kp_traf_vol_day_30d',
            'kp_traf_vol_day_90d',
            'kp_traf_vol_day_360d',
            'st_traf_vol_day_7d',
            'st_traf_vol_day_30d',
            'st_traf_vol_day_90d',
            'st_traf_vol_day_360d',
            'wi_traf_vol_day_7d',
            'wi_traf_vol_day_30d',
            'wi_traf_vol_day_90d',
            'wi_traf_vol_day_360d',
            'okko_traf_vol_day_7d',
            'okko_traf_vol_day_30d',
            'okko_traf_vol_day_90d',
            'okko_traf_vol_day_360d',
            'ivi_traf_vol_day_7d',
            'ivi_traf_vol_day_30d',
            'ivi_traf_vol_day_90d',
            'ivi_traf_vol_day_360d',
            'pr_traf_vol_day_7d',
            'pr_traf_vol_day_30d',
            'pr_traf_vol_day_90d',
            'pr_traf_vol_day_360d',
            'am_traf_vol_day_7d',
            'am_traf_vol_day_30d',
            'am_traf_vol_day_90d',
            'am_traf_vol_day_360d',
            'nf_traf_vol_day_7d',
            'nf_traf_vol_day_30d',
            'nf_traf_vol_day_90d',
            'nf_traf_vol_day_360d',
            'fl_bound_card',
            'pay_method_cd',
            'pay_method_name',
            'payer_type_cd',
            'payer_type_name',
            'payment_card_type_day_30d',
            'payment_card_type_day_90d',
            'fl_ewallet_payment_day_30d',
            'fl_ewallet_payment_day_90d',
            'fl_card_payment_day_30d',
            'fl_card_payment_day_90d',
            'fl_cash_payment_day_30d',
            'fl_cash_payment_day_90d',
            'expected_payment_payday',
            'fl_sbp_payment_day_30d',
            'fl_sbp_payment_day_90d',
            'cnt_premium_paid_day_90d',
            'cnt_premium_paid_day_180d',
            'cnt_premium_paid_day_360d',
            'fl_unpaid_last_prompay',
            'sum_unpaid_last_prompay',
            'cnt_prompay_day_7d',
            'cnt_attempts_activation_prompay_day_7d',
            'sum_prompay_day_7d',
            'clc_comission_prompay_day_7d',
            'sum_paid_comission_prompay_day_7d',
            'sum_unpaid_comission_prompay_day_7d',
            'cnt_prompay_day_30d',
            'cnt_attempts_activation_prompay_day_30d',
            'cnt_paid_prompay_day_30d',
            'sum_prompay_day_30d',
            'cnt_paid_prompay_day_90d',
            'sum_prompay_day_90d',
            'current_block_cd',
            'current_block_dur',
            'current_block_name',
            'unblock_limit',
            'fl_ban_calling',
            'fl_ban_mailing_email',
            'fl_ban_sms',
            'fl_unsub_email_cashback',
            'fl_unsub_email_kion',
            'fl_unsub_email_live',
            'fl_unsub_email_mts',
            'fl_unsub_email_music',
            'fl_unsub_email_payment',
            'fl_unsub_email_premium',
            'fl_email_comm_day_30d',
            'fl_email_comm_day_90d',
            'fl_email_comm_day_180d',
            'fl_email_comm_day_360d',
            'cnt_request_claim_day_30d',
            'cnt_request_day_30d',
            'geo_day_bs_city',
            'geo_day_bs_city_popul_type',
            'geo_night_bs_city',
            'geo_night_bs_city_popul_type',
            'geo_night_bs_district_msk',
            'geo_night_bs_region',
            'time_zone',
            'time_zone_geo',
            'personal_data_block_date',
            'personal_data_status',
            'personal_data_verify_source_name',
            'rate_comission'
        )
    )

    return daily_features

if __name__ == "__main__":
    spark = SparkSession.builder \
        .appName("build_gr_datamart") \
        .master("spark://spark-master:7077") \
        .config("spark.sql.catalogImplementation", "hive") \
        .config("spark.sql.warehouse.dir", "hdfs://namenode:9000/user/hive/warehouse") \
        .enableHiveSupport() \
        .getOrCreate()
    
    logical_date = datetime.now().date()
try:
    final_df = build_gr_mobile_datamart(spark, logical_date, logger)
    (
        final_df
        .repartition(4)
        .write
        .mode("overwrite")
        .format("orc")
        .saveAsTable("spfix_dm.mob_features_dm__1__base")
    )

finally:
    spark.stop()